CREATE EXTENSION IF NOT EXISTS postgis;
-- -----------------------------
-- Table Users
-- -----------------------------
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	-- Auto increment + sequence interne + compatibility with flask
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    is_admin BOOLEAN DEFAULT FALSE
);
-- -----------------------------
-- Tables images
-- -----------------------------
CREATE TABLE image_post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(400) NOT NULL,
    image_data BYTEA NOT NULL,
    image_mime_type VARCHAR(50) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
-- -----------------------------
-- Tables reviews
-- -----------------------------
CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    comment VARCHAR(400) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    image_post_id BIGINT NOT NULL REFERENCES image_post(id) ON DELETE CASCADE
);
-- -----------------------------
-- Enum Place
-- -----------------------------
CREATE TYPE place_enum AS ENUM (
    'region',
    'foret',
    'montagne',
    'forteresse',
    'ville',
    'capitale',
    'eau',
    'ruine',
    'dark',
    'mine',
    'port',
    'pont',
    'plaine',
    'chemin',
    'monument',
    'special',
    'default'
);
-- -----------------------------
-- Table Places
-- -----------------------------
CREATE TABLE places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(200) NOT NULL UNIQUE,
    type_place place_enum NOT NULL,
    description TEXT NOT NULL,
    image_url VARCHAR(500),
    parent_id BIGINT REFERENCES places(id) ON DELETE SET NULL
	-- Garde les lieux enfants même si le parent est supprimé
);
-- -----------------------------
-- Table Races
-- -----------------------------
CREATE TABLE races (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(50) NOT NULL UNIQUE,
    weakness VARCHAR(255) NOT NULL,
    strength VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
	citation VARCHAR(400)
);
-- -----------------------------
-- Table Relation Types
-- -----------------------------
CREATE TABLE relation_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);
-- -----------------------------
-- Table History
-- -----------------------------
CREATE TABLE history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
	citation VARCHAR(400),
    start_year SMALLINT,
    end_year SMALLINT,
    era VARCHAR(25),
    place_id BIGINT REFERENCES places(id),
    relation_type_id BIGINT REFERENCES relation_types(id),
    UNIQUE(name, start_year, place_id)
);
-- -----------------------------
-- Table Characters
-- -----------------------------
CREATE TABLE characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(100) NOT NULL UNIQUE,
    birth_date SMALLINT,
    death_date SMALLINT,
    era_birth VARCHAR(25) NOT NULL,
    era_death VARCHAR(25),
    gender VARCHAR(10) NOT NULL,
    profession VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
	citation VARCHAR(400),
    race_id BIGINT REFERENCES races(id)
);
-- -----------------------------
-- Tables Map avec PostGIS
-- -----------------------------
CREATE TABLE map_region (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(100) NOT NULL UNIQUE,
    shape_data GEOMETRY(POLYGON, 0) NOT NULL,
    place_id BIGINT REFERENCES places(id)
);

-- Création de l'ENUM pour les catégories de marqueurs
CREATE TYPE marker_type AS ENUM (
    'foret',
    'montagne',
    'forteresse',
    'ville',
    'capitale',
    'eau',
    'ruine',
    'dark',
    'mine',
    'port',
    'pont',
    'plaine',
    'chemin',
    'monument',
    'special',
    'default'
);

CREATE TABLE map_marker (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(100) NOT NULL UNIQUE,
    location GEOMETRY(POINT, 0) NOT NULL,
    type marker_type NOT NULL DEFAULT 'default',
    place_id BIGINT REFERENCES places(id)
);

CREATE TABLE descriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(50) NOT NULL CHECK (
		entity_type IN (
			'character', 'place', 'race', 'history', 'region',
			'foret', 'montagne', 'forteresse', 'ville', 'capitale',
			'eau', 'ruine', 'dark', 'mine', 'port', 'pont',
			'plaine', 'chemin', 'monument', 'special', 'default'
		)
	),
    entity_id BIGINT NOT NULL,
    title VARCHAR(100),
    content TEXT NOT NULL,
    order_index INT DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(entity_type, entity_id, order_index)
);
